import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const hindiTranslations = [
  { key: 'home', value: 'होम' },
  { key: 'shop', value: 'खरीदें' },
  { key: 'products', value: 'उत्पाद' },
  { key: 'cart', value: 'कार्ट' },
  { key: 'checkout', value: 'चेकआउट' },
  { key: 'login', value: 'लॉगिन' },
  { key: 'register', value: 'रजिस्टर' },
  { key: 'logout', value: 'लॉगआउट' },
  { key: 'profile', value: 'प्रोफ़ाइल' },
  { key: 'orders', value: 'ऑर्डर' },
  { key: 'wishlist', value: 'विशलिस्ट' },
  { key: 'search', value: 'खोजें' },
  { key: 'categories', value: 'श्रेणियां' },
  { key: 'price', value: 'कीमत' },
  { key: 'add_to_cart', value: 'कार्ट में जोड़ें' },
  { key: 'buy_now', value: 'अभी खरीदें' },
  { key: 'out_of_stock', value: 'स्टॉक में नहीं' },
  { key: 'in_stock', value: 'स्टॉक में' },
  { key: 'free_shipping', value: 'मुफ्त शिपिंग' },
  { key: 'new_arrivals', value: 'नए आगमन' },
  { key: 'best_sellers', value: 'बेस्ट सेलर' },
  { key: 'featured', value: 'विशेष' },
  { key: 'sale', value: 'सौदा' },
  { key: 'total', value: 'कुल' },
  { key: 'subtotal', value: 'उप-योग' },
  { key: 'shipping', value: 'शिपिंग' },
  { key: 'tax', value: 'कर' },
  { key: 'discount', value: 'छूट' },
  { key: 'place_order', value: 'ऑर्डर करें' },
  { key: 'continue_shopping', value: 'खरीदारी जारी रखें' },
  { key: 'view_cart', value: 'कार्ट देखें' },
  { key: 'empty_cart', value: 'कार्ट खाली है' },
  { key: 'no_products', value: 'कोई उत्पाद नहीं' },
  { key: 'loading', value: 'लोड हो रहा है...' },
  { key: 'error', value: 'त्रुटि' },
  { key: 'success', value: 'सफल' },
  { key: 'quantity', value: 'मात्रा' },
  { key: 'size', value: 'आकार' },
  { key: 'color', value: 'रंग' },
  { key: 'description', value: 'विवरण' },
  { key: 'reviews', value: 'समीक्षाएं' },
  { key: 'write_review', value: 'समीक्षा लिखें' },
  { key: 'contact_us', value: 'संपर्क करें' },
  { key: 'about_us', value: 'हमारे बारे में' },
  { key: 'faq', value: 'सामान्य प्रश्न' },
  { key: 'terms', value: 'नियम और शर्तें' },
  { key: 'privacy', value: 'गोपनीयता नीति' },
  { key: 'return_policy', value: 'रिटर्न नीति' },
  { key: 'track_order', value: 'ऑर्डर ट्रैक करें' },
  { key: 'order_placed', value: 'ऑर्डर प्लेस' },
  { key: 'order_confirmed', value: 'ऑर्डर की पुष्टि' },
  { key: 'order_shipped', value: 'ऑर्डर शिप' },
  { key: 'order_delivered', value: 'ऑर्डर डिलीवर' },
  { key: 'payment', value: 'भुगतान' },
  { key: 'online', value: 'ऑनलाइन' },
  { key: 'cod', value: 'कैश ऑन डिलीवरी' },
  { key: 'address', value: 'पता' },
  { key: 'phone', value: 'फ़ोन' },
  { key: 'email', value: 'ईमेल' },
  { key: 'name', value: 'नाम' },
  { key: 'first_name', value: 'पहला नाम' },
  { key: 'last_name', value: 'अंतिम नाम' },
  { key: 'city', value: 'शहर' },
  { key: 'state', value: 'राज्य' },
  { key: 'pincode', value: 'पिनकोड' },
  { key: 'country', value: 'देश' },
  { key: 'save', value: 'सहेजें' },
  { key: 'cancel', value: 'रद्द करें' },
  { key: 'delete', value: 'हटाएं' },
  { key: 'edit', value: 'संपादित करें' },
  { key: 'update', value: 'अपडेट' },
  { key: 'confirm', value: 'पुष्टि करें' },
  { key: 'yes', value: 'हां' },
  { key: 'no', value: 'नहीं' },
  { key: 'apply', value: 'लागू करें' },
  { key: 'remove', value: 'हटाएं' },
  { key: 'coupon_code', value: 'कूपन कोड' },
  { key: 'apply_coupon', value: 'कूपन लागू करें' },
  { key: 'invalid_coupon', value: 'अमान्य कूपन' },
  { key: 'coupon_applied', value: 'कूपन लागू' },
  { key: 'newsletter', value: 'न्यूज़लेटर' },
  { key: 'subscribe', value: 'सब्सक्राइब करें' },
  { key: 'subscribed', value: 'सब्सक्राइब किया' },
  { key: 'thank_you', value: 'धन्यवाद' },
  { key: 'view_all', value: 'सभी देखें' },
  { key: 'filter', value: 'फ़िल्टर' },
  { key: 'sort', value: 'क्रमबद्ध करें' },
  { key: 'newest', value: 'नवीनतम' },
  { key: 'price_low_high', value: 'कम से अधिक कीमत' },
  { key: 'price_high_low', value: 'अधिक से कम कीमत' },
  { key: 'popular', value: 'लोकप्रिय' },
  { key: 'flash_sale', value: 'फ्लैश सेल' },
  { key: 'ends_in', value: 'समाप्त होता है' },
  { key: 'days', value: 'दिन' },
  { key: 'hours', value: 'घंटे' },
  { key: 'minutes', value: 'मिनट' },
  { key: 'seconds', value: 'सेकंड' },
  { key: 'customers_also_bought', value: 'ग्राहकों ने भी खरीदा' },
  { key: 'you_may_like', value: 'आपको पसंद आ सकता है' },
  { key: 'vendor', value: 'विक्रेता' },
  { key: 'become_vendor', value: 'विक्रेता बनें' },
  { key: 'vendor_dashboard', value: 'विक्रेता डैशबोर्ड' },
  { key: 'my_products', value: 'मेरे उत्पाद' },
  { key: 'add_product', value: 'उत्पाद जोड़ें' },
  { key: 'product_added', value: 'उत्पाद जोड़ा गया' },
  { key: 'order_received', value: 'ऑर्डर प्राप्त' },
  { key: 'process_order', value: 'ऑर्डर प्रोसेस करें' },
  { key: 'ship_order', value: 'ऑर्डर शिप करें' },
  { key: 'earnings', value: 'कमाई' },
  { key: 'withdraw', value: 'निकालें' },
  { key: 'pending', value: 'लंबित' },
  { key: 'approved', value: 'स्वीकृत' },
  { key: 'rejected', value: 'अस्वीकृत' },
  { key: 'return', value: 'रिटर्न' },
  { key: 'return_request', value: 'रिटर्न अनुरोध' },
  { key: 'refund', value: 'रिफंड' },
  { key: 'wallet', value: 'वॉलेट' },
  { key: 'loyalty_points', value: 'लॉयल्टी पॉइंट्स' },
  { key: 'redeem_points', value: 'पॉइंट्स रिडीम करें' },
  { key: 'earn_points', value: 'पॉइंट्स कमाएं' },
]

async function main() {
  console.log('Seeding Hindi translations...')
  
  for (const { key, value } of hindiTranslations) {
    await prisma.translation.upsert({
      where: { locale_key: { locale: 'hi', key } },
      update: { value },
      create: { locale: 'hi', key, value },
    })
  }
  
  console.log(`Seeded ${hindiTranslations.length} Hindi translations`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())